name: Upload Website
 
on:

  push:

    branches:

    - main
 
jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout

      uses: actions/checkout@v1
 
    - name: Configure AWS Credentials

      uses: aws-actions/configure-aws-credentials@v1

      with:

        aws-access-key-id: ${{ secrets.AKIA3P4NIY4KXTUBXTUJ}}

        aws-secret-access-key: ${{ secrets.DYraK7bG4CemFpRTPg1ulpeSyQrVb/wsOf4Ickqq }}

        aws-region: us-east-1
 
    - name: Deploy static site to S3 bucket

      run: aws s3 sync ./ s3://devops-bucket5171  --delete
 
