name: Build and Push to ECR

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=swiggy
            -Dsonar.projectName=swiggy
            -Dsonar.sources=.

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 790033385237.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t devops-ank-25 .

      - name: Tag Docker image for ECR
        run: |
          docker tag devops-ank-25:latest 790033385237.dkr.ecr.us-east-1.amazonaws.com/devops-ank-25:latest

      - name: Push Docker image to ECR
        run: |
          docker push 790033385237.dkr.ecr.us-east-1.amazonaws.com/devops-ank-25:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Docker pull image
        run: docker pull 790033385237.dkr.ecr.us-east-1.amazonaws.com/devops-ank-25:latest

      - name: Image scan
        run: trivy image 790033385237.dkr.ecr.us-east-1.amazonaws.com/devops-ank-25:latest > trivyimagedeploy.txt

      - name: Stop and remove existing container
        run: |
          docker stop swiggy-clone || true
          docker rm swiggy-clone || true

      - name: Deploy to container
        run: docker run -d --name swiggy-clone -p 3000:3000 790033385237.dkr.ecr.us-east-1.amazonaws.com/devops-ank-25:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks --region us-east-1 update-kubeconfig --name EKS_CLOUD

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment-service.yml --validate=false
